StackITmvc/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StackITmvc.Data;
using StackITmvc.Models;

namespace StackITmvc.Controllers
{   
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly StackItContext _context;

        public CustomersController(StackItContext context)
        {
            _context = context;
        }
        //[Authorize (Roles = "StackIt")]
        // GET: Customers
        public async Task<IActionResult> Index(string searchString)
        {
            var customers = from c in _context.Customer
                         select c;

            if (!String.IsNullOrEmpty(searchString))
            {   
               customers = customers.Where(s => s.CompanyName.Contains(searchString));
            }

            return View(await customers.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,CompanyName,VAT,StreetName,StreetNo,PostalCode,City,Country,PhoneNo,Email")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,CompanyName,VAT,StreetName,StreetNo,PostalCode,City,Country,PhoneNo,Email")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.FindAsync(id);
            _context.Customer.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.CustomerId == id);
        }
    }
}

StackITmvc/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StackITmvc.Data;
using StackITmvc.Models;

namespace StackITmvc.Controllers
{
    [Authorize]
    public class JobsController : Controller
    {
        private readonly StackItContext _context;

        public JobsController(StackItContext context)
        {
            _context = context;
        }

        // GET: Jobs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Job.ToListAsync());
        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("JobId,JobName")] Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job.FindAsync(id);
            if (job == null)
            {
                return NotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("JobId,JobName")] Job job)
        {
            if (id != job.JobId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.JobId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job = await _context.Job.FindAsync(id);
            _context.Job.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(int id)
        {
            return _context.Job.Any(e => e.JobId == id);
        }
    }
}

StackITmvc/Controllers/K_AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StackITmvc.Data;
using StackITmvc.Models;

namespace StackITmvc.Controllers
{
    [Authorize]
    public class K_AdminsController : Controller
    {
        private readonly StackItContext _context;
        private readonly UserManager<User> userManager;
        private readonly IPasswordHasher<User> passwordHasher;
        private readonly SignInManager<User> signInManager;
        private readonly RoleManager<IdentityRole<int>> roleManager;

        public K_AdminsController(StackItContext context, 
                                  UserManager<User> userManager,
                                  IPasswordHasher<User> passwordHasher,
                                  SignInManager<User> signInManager,
                                  RoleManager<IdentityRole<int>> roleManager)
        {
            _context = context;
            this.userManager = userManager;
            this.passwordHasher = passwordHasher;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
        }

        //[Authorize (Roles = "StackIt")]
        // GET: K_Admins
        public IActionResult Index()
        {
            List<User> adminUsers = _context.Users.Where(x => x.AuthorizationLevel == AuthorizationLevel.K_Admin).Include(i => i.Company).ToList();
            return View(adminUsers);
        }

        // GET: K_Admins/Details/5
        public async Task<IActionResult> Details(int id)
        {

            var k_Admin = await _context.Users
                .Include(k => k.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (k_Admin == null)
            {
                return NotFound();
            }

            return View(k_Admin);
        }

        // GET: K_Admins/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CompanyName");
            return View();
        }

        // POST: K_Admins/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( User k_Admin)
        {
            if (ModelState.IsValid)
            {
                User user = new User
                {
                    UserName = k_Admin.Email,
                    Email = k_Admin.Email,
                    AuthorizationLevel = AuthorizationLevel.K_Admin,
                    FirstName = k_Admin.FirstName,
                    LastName = k_Admin.LastName,
                    CustomerId = k_Admin.CustomerId,
                    Password = k_Admin.Password,
                    PhoneNumber = k_Admin.PhoneNumber,
                    ConfirmPassword = k_Admin.ConfirmPassword,
                    PasswordHash = k_Admin.PasswordHash
                };

                var role = roleManager.Roles.SingleOrDefault(s => s.Name == "K_Admin");

                IdentityResult result = await userManager.CreateAsync(user, user.Password);
                if (result.Succeeded) { 
                    //Adds the role to the user in Identity
                    await userManager.AddToRoleAsync(user, role.Name);
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (IdentityError error in result.Errors)
                        ModelState.AddModelError("", error.Description);
                }
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CompanyName", k_Admin.CustomerId);
            return View(k_Admin);
        }

        // GET: K_Admins/Edit/5
        public async Task<IActionResult> Edit(int id)
        {

            var k_Admin = await _context.Users.FindAsync(id);
            if (k_Admin == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CompanyName", k_Admin.CustomerId);
            return View(k_Admin);
        }

        // POST: K_Admins/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit
            (
                string id, 
                string email, 
                string password, 
                string firstName, 
                string lastName, 
                string phoneNumber, 
                [Bind("CustomerId")] User k_Admin
            )
        {
            User user = await userManager.FindByIdAsync(id);
            if (user != null)
            {
                if (!string.IsNullOrEmpty(email))
                    user.Email = email;
                else
                    ModelState.AddModelError("", "Email cannot be empty");

                if (!string.IsNullOrEmpty(email))
                    user.UserName = email;
                else
                    ModelState.AddModelError("", "User Name cannot be empty");

                if (!string.IsNullOrEmpty(password))
                {
                    user.PasswordHash = passwordHasher.HashPassword(user, password);
                    user.Password = password;
                    user.ConfirmPassword = password;
                } 
                else
                    ModelState.AddModelError("", "Password cannot be empty");

                if (!string.IsNullOrEmpty(firstName))
                    user.FirstName = firstName;
                else
                    ModelState.AddModelError("", "First Name cannot be empty");

                if (!string.IsNullOrEmpty(lastName))
                    user.LastName = lastName;
                else
                    ModelState.AddModelError("", "Last Name cannot be empty");

                if (!string.IsNullOrEmpty(phoneNumber))
                    user.PhoneNumber = phoneNumber;
                else
                    ModelState.AddModelError("", "Phone Number cannot be empty");

                if (!string.IsNullOrEmpty(email) && !string.IsNullOrEmpty(password))
                {
                    IdentityResult result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                        return RedirectToAction("Index");
                    else
                        Errors(result);
                }
            }
            else
                ModelState.AddModelError("", "User Not Found");
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CompanyName", k_Admin.CustomerId);
            return View(user);
        }

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        // GET: K_Admins/Delete/5
        public async Task<IActionResult> Delete(int id)
        {

            var k_Admin = await _context.Users
                .Include(k => k.Company)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (k_Admin == null)
            {
                return NotFound();
            }

            return View(k_Admin);
        }

        // POST: K_Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var k_Admin = await _context.Users.FindAsync(id);

            //fjern fra sub
            var adminSubscriptions = _context.UserSubscriptions.Where(i => i.UserId == id).SingleOrDefault();
            if(adminSubscriptions != null)
            {
                _context.UserSubscriptions.Remove(adminSubscriptions);
            }
            _context.Users.Remove(k_Admin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool K_AdminExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

StackITmvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/d17f325ac5.js" crossorigin="anonymous"></script>
    <title>@ViewData["Title"] - StackIT WebPortal</title>
    <link rel="stylesheet" href="~/css/stylesheet.css" />
</head>
<body>

    <div class="wrapper">

        <header class="h">

            <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="header__link"><img src="@Url.Content("Image/Icons/logo1.png")"> <div> - Web Portal </div></a>

            <div class="login-person">
                @*If the user is signed-in display Logout link*@
                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-controller="Login" asp-action="Logout">
                        <button type="submit" style="width:auto"
                                class="nav-link btn btn-link py-0">
                            Sign Out <u>@User.Identity.Name</u> <i class="fas fa-sign-out-alt"></i>
                        </button>
                    </form>
                }
                else
                {
                    <a class="nav-link" asp-controller="Login" asp-action="Login">
                        Login
                    </a>
                }
            </div>
        </header>

        <aside class="n">
            <nav class="navbar">
                @if (User.Identity.IsAuthenticated && User.IsInRole("StackIt"))
                {
                <ul>
                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-building"></i>
                            Customer
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Index">All Customers</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Customers" asp-action="Create">Create Customer</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-user-shield"></i>
                            K_Admin
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="K_Admins" asp-action="Index">All Company Admins</a>
                            <a class="navbar-brand" asp-area="" asp-controller="K_Admins" asp-action="Create">Create Company Admin</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-user-cog"></i>
                            Operators
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="k_Operators" asp-action="Index">All Operators</a>
                            <a class="navbar-brand" asp-area="" asp-controller="k_Operators" asp-action="Create">Create Operator</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-tasks"></i>
                            Subsicription
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Subscriptions" asp-action="Index">All subscriptions</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Subscriptions" asp-action="Create">Create subscription</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fa fa-cogs"></i>
                            Job
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Index">All Jobs</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Create">Create Job</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-hdd"></i>
                            Hardwares
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Hardwares" asp-action="Index">All Hardwares</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Hardwares" asp-action="Create">Create Hardware</a>
                        </div>
                    </li>
                </ul>
                }
                @if (User.Identity.IsAuthenticated && User.IsInRole("K_Admin"))
                {
                <ul>
                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-user-cog"></i>
                            Operators
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="k_Operators" asp-action="Index">All Operators</a>
                            <a class="navbar-brand" asp-area="" asp-controller="k_Operators" asp-action="Create">Create Operator</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-tasks"></i>
                            Subsicription
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Subscriptions" asp-action="Index">All subscriptions</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Subscriptions" asp-action="Create">Create subscription</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fa fa-cogs"></i>
                            Job
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Index">All Jobs</a>
                            <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Create">Create Job</a>
                        </div>
                    </li>
                </ul>
                }
                @if (User.Identity.IsAuthenticated && User.IsInRole("K_Operator"))
                {
                <ul>
                    <li>
                        <button class="dropdown-btn">
                            <i class="fas fa-tasks"></i>
                            Subsicription
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Subscriptions" asp-action="Index">All subscriptions</a>
                        </div>
                    </li>

                    <li>
                        <button class="dropdown-btn">
                            <i class="fa fa-cogs"></i>
                            Job
                            <i class="fa fa-caret-down"></i>
                        </button>
                        <div class="dropdown-container">
                            <a class="navbar-brand" asp-area="" asp-controller="Jobs" asp-action="Index">All Jobs</a>
                        </div>
                    </li>
                </ul>
                }
            </nav>
        </aside>

        <div class="container m">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

StackITmvc/Views/Shared/_homePage.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pages</title>
    <link rel="stylesheet" href="~/css/stylesheet.css" />
    <script src="https://kit.fontawesome.com/d17f325ac5.js" crossorigin="anonymous"></script>
</head>
<body>

    @Html.Partial("Partials/Header")

    <main class="container">
        @RenderBody()
    </main>

    @Html.Partial("Partials/Footer")




</body>
</html>